### ISSUE TITLE
RecyclerView Problem

### ISSUE THREAD

**Issue by long1eu** [davideas/FlipView#15]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/9283414/25758604/e3a609b6-31d7-11e7-802f-f184684d3fdf.gif)

This is the demo project. Any ideas?
https://github.com/thelong1EU/FlipViewDemo

**Comment by davideas** [comment]
@thelong1EU, took 1h to install APK due to different configuration and versions.
But I finally verified that you miss to notify when the FlipView should be bound flipped or not, so you have to check if the item is selected with `holder.icon.flipSilently(selectedBooks.contains(talk));` inside `onBindViewHolder()`.
Also you don't need to bind the item when you select or unselect the single FlipView.

However, I strongly suggest to use my other library `FlexibleAdapter`. which will help you in the selection, ActionMode and make your code easier to mantain and to bind views.
More over for you, I was able to not rebound any views when we select or unselect all items, it means that the animations of the views inside the items will complete naturally.

**Comment by long1eu** [comment]
Thanks so much! I will take a look at the FlexibleAdapter. When we meet I'll give you a :beer:
